# Configuration file for the LawyerUp-HittheGym-DeleteFacebook reddit bot
---

account:
  username: 'LU-HG-DF-bot'
  password: ''

reddit: 'r/circlejerk/new'
seen_file: 'seen.txt'
comment_file: 'comment.md'
wait: 10

server:
  port: 8081
